pipeline {

    parameters {
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')    } 

   agent  any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']],
                          userRemoteConfigs: [[url: 'https://github.com/sivaganga9786/Devopsfactory-2024.git', credentialsId: 'github']]])
            }
        }
            }

        stage('Plan') {
            steps {
                sh 'pwd;cd Terraform/terraform/ ; terraform init'
                sh "pwd;cd Terraform/terraform/ ; terraform plan -out tfplan"
                sh 'pwd;cd Terraform/terraform/ ; terraform show -no-color tfplan > tfplan.txt'
            }
        }
        stage('Approval') {
           when {
               not {
                   equals expected: true, actual: params.autoApprove
               }
           }

           steps {
               script {
                    def plan = readFile 'terraform/tfplan.txt'
                    input message: "Do you want to apply the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
               }
           }
       }

        stage('Apply') {
            steps {
                sh "pwd;cd Terraform/terraform/ ; terraform apply -input=false tfplan"
            }
        }
    }

  }